apiVersion: v1
kind: Namespace
metadata:
  name: default
---
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: default
spec:
  ports:
    - port: 2181
      name: client
  clusterIP: None  # headless so StatefulSet DNS works
  selector:
    app: zookeeper
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: default
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
        - name: zookeeper
          image: zookeeper:3.9.1
          ports:
            - containerPort: 2181
              name: client
          env:
            - name: ZOO_PORT
              value: "2181"
            - name: ZOO_DATA_DIR
              value: "/data"
          volumeMounts:
            - name: datadir
              mountPath: /data
      volumes:
        - name: datadir
          emptyDir: {}
